-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 13:59:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kukuimid_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kukuimid_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kukuimid_db` ;
USE `kukuimid_db` ;

-- -----------------------------------------------------
-- Table `kukuimid_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukuimid_db`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(55) NULL,
  `password` VARCHAR(55) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kukuimid_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukuimid_db`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `monto_pedido` DOUBLE NULL,
  `fecha_envio` DATE NULL,
  `fecha_entrega` DATE NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idpedidos`, `usuarios_idusuarios`),
  INDEX `fk_pedidos_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `kukuimid_db`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kukuimid_db`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukuimid_db`.`direccion` (
  `iddireccion` INT NOT NULL,
  `calle` VARCHAR(70) NULL,
  `colonia` VARCHAR(45) NULL,
  `codigopostal` VARCHAR(45) NULL,
  `ciudad` VARCHAR(100) NULL,
  `estado` VARCHAR(80) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`iddireccion`, `usuarios_idusuarios`),
  INDEX `fk_direccion_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `kukuimid_db`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kukuimid_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukuimid_db`.`producto` (
  `idproducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `descripcion` TEXT(1000) NULL,
  `precio` DOUBLE NULL,
  `imagen` VARCHAR(100) NULL,
  `tamaño` VARCHAR(45) NULL,
  `pedidos_idpedidos` INT NOT NULL,
  PRIMARY KEY (`idproducto`, `pedidos_idpedidos`),
  INDEX `fk_producto_pedidos_idx` (`pedidos_idpedidos` ASC) VISIBLE,
  CONSTRAINT `fk_producto_pedidos`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `kukuimid_db`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
